import Link from 'next/link';
import { db } from '@/lib/db';
import { Plus, ArrowUpRight, FileText } from 'lucide-react';
const labels: Record<string, string> = { DRAFT: 'Rascunho', IN_REVIEW: 'Em revisão', APPROVED: 'Aprovado', REJECTED: 'Rejeitado', SCHEDULED: 'Agendado', PUBLISHED: 'Publicado', FAILED: 'Falha' };
export default async function Contents() {
  const [contents, profiles] = await Promise.all([db.content.findMany({ include: { profile: true, template: true }, orderBy: { updatedAt: 'desc' }, take: 50 }), db.profile.findMany({ orderBy: { name: 'asc' } })]);
  return <><div className="page-heading"><div><span className="eyebrow">VISÃO GERAL</span><h1>Seu conteúdo começa aqui.</h1><p>Planeje, crie e acompanhe cada peça da equipe em um só lugar.</p></div><Link href="/conteudos/novo" className="button primary"><Plus size={18} /> Novo conteúdo</Link></div><div className="metrics"><div className="metric"><span>CONTEÚDOS</span><strong>{contents.length.toString().padStart(2, '0')}</strong><small>Peças criadas no estúdio</small></div><div className="metric"><span>EM REVISÃO</span><strong>{contents.filter(x => x.status === 'IN_REVIEW').length.toString().padStart(2, '0')}</strong><small>Aguardando aprovação</small></div><div className="metric"><span>APROVADOS</span><strong>{contents.filter(x => x.status === 'APPROVED').length.toString().padStart(2, '0')}</strong><small>Prontos para exportar</small></div><div className="metric accent"><span>PERFIS ATIVOS</span><strong>{profiles.length.toString().padStart(2, '0')}</strong><small>Identidades configuráveis</small></div></div><div className="section-head"><div><span className="eyebrow">PRODUÇÃO</span><h2>Conteúdos recentes</h2></div><Link href="/conteudos/novo" className="text-link">Criar novo <ArrowUpRight size={16} /></Link></div>{contents.length ? <div className="content-list">{contents.map(item => <Link className="content-row" href={`/conteudos/${item.id}`} key={item.id}><div className="row-icon"><FileText size={20} /></div><div className="row-main"><strong>{item.title || item.topic}</strong><span>{item.template.name} · {item.profile.name}</span></div><span className={`badge badge-${item.status.toLowerCase()}`}>{labels[item.status]}</span><span className="row-date">{item.updatedAt.toLocaleDateString('pt-BR')}</span><ArrowUpRight size={17} /></Link>)}</div> : <div className="empty-state"><div className="empty-icon"><PenLine size={26} /></div><h3>Sua primeira peça está a um clique.</h3><p>Escolha um perfil e um modelo para criar sua primeira arte com legenda.</p><Link href="/conteudos/novo" className="button primary">Criar primeira peça <ArrowUpRight size={16} /></Link></div>}</>;
}
function PenLine(props: { size: number }) { return <FileText {...props} />; }
