services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: azul
      POSTGRES_PASSWORD: azul
      POSTGRES_DB: azul360_studio
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
