// 30 redações e portais editoriais distintos. O cadastro de um endereço não
// significa que exista RSS público: a coleta registra o êxito ou a falha.
// Um canal por marca, sem repetir unidades regionais da mesma rede.
export const portalCatalog = [
  { slug: 'agencia-brasil', name: 'Agência Brasil · Economia', homepageUrl: 'https://agenciabrasil.ebc.com.br/economia', feedUrl: 'https://agenciabrasil.ebc.com.br/rss/economia/feed.xml' },
  { slug: 'sebrae', name: 'Agência Sebrae', homepageUrl: 'https://agenciasebrae.com.br/', feedUrl: 'https://agenciasebrae.com.br/feed/' },
  { slug: 'infomoney', name: 'InfoMoney', homepageUrl: 'https://www.infomoney.com.br/economia/' },
  { slug: 'exame', name: 'Exame', homepageUrl: 'https://exame.com/economia/' },
  { slug: 'cnn-brasil', name: 'CNN Brasil Money', homepageUrl: 'https://www.cnnbrasil.com.br/money/' },
  { slug: 'neofeed', name: 'NeoFeed', homepageUrl: 'https://neofeed.com.br/' },
  { slug: 'brazil-journal', name: 'Brazil Journal', homepageUrl: 'https://braziljournal.com/' },
  { slug: 'seu-dinheiro', name: 'Seu Dinheiro', homepageUrl: 'https://www.seudinheiro.com/' },
  { slug: 'money-times', name: 'Money Times', homepageUrl: 'https://www.moneytimes.com.br/' },
  { slug: 'poder360', name: 'Poder360', homepageUrl: 'https://www.poder360.com.br/economia/' },
  { slug: 'diario-comercio', name: 'Diário do Comércio', homepageUrl: 'https://diariodocomercio.com.br/economia/' },
  { slug: 'valor', name: 'Valor Econômico', homepageUrl: 'https://valor.globo.com/' },
  { slug: 'contabeis', name: 'Portal Contábeis', homepageUrl: 'https://www.contabeis.com.br/noticias/' },
  { slug: 'investnews', name: 'InvestNews', homepageUrl: 'https://investnews.com.br/tag/credito/' },
  { slug: 'bloomberg-linea', name: 'Bloomberg Línea Brasil', homepageUrl: 'https://www.bloomberglinea.com.br/' },
  { slug: 'forbes', name: 'Forbes Brasil', homepageUrl: 'https://forbes.com.br/' },
  { slug: 'istoe-dinheiro', name: 'IstoÉ Dinheiro', homepageUrl: 'https://istoedinheiro.com.br/' },
  { slug: 'estadao', name: 'Estadão Economia', homepageUrl: 'https://www.estadao.com.br/economia/' },
  { slug: 'folha', name: 'Folha Mercado', homepageUrl: 'https://www1.folha.uol.com.br/mercado/' },
  { slug: 'jornal-comercio', name: 'Jornal do Comércio', homepageUrl: 'https://www.jornaldocomercio.com/economia/' },
  { slug: 'diario-nordeste', name: 'Diário do Nordeste Negócios', homepageUrl: 'https://diariodonordeste.verdesmares.com.br/negocios' },
  { slug: 'gazeta-povo', name: 'Gazeta do Povo Economia', homepageUrl: 'https://www.gazetadopovo.com.br/economia/' },
  { slug: 'metropoles', name: 'Metrópoles Negócios', homepageUrl: 'https://www.metropoles.com/negocios' },
  { slug: 'correio-braziliense', name: 'Correio Braziliense Economia', homepageUrl: 'https://www.correiobraziliense.com.br/economia/' },
  { slug: 'sbt-news', name: 'SBT News', homepageUrl: 'https://sbtnews.sbt.com.br/' },
  { slug: 'r7', name: 'R7 Economia', homepageUrl: 'https://noticias.r7.com/economia' },
  { slug: 'carta-capital', name: 'CartaCapital Economia', homepageUrl: 'https://www.cartacapital.com.br/economia/' },
  { slug: 'brasil-de-fato', name: 'Brasil de Fato', homepageUrl: 'https://www.brasildefato.com.br/' },
  { slug: 'a-tarde', name: 'A Tarde Economia', homepageUrl: 'https://atarde.com.br/economia' },
  { slug: 'estado-minas', name: 'Estado de Minas Economia', homepageUrl: 'https://www.em.com.br/economia/' },
] as const;
